version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: registerappform-app:latest
    container_name: registerappform-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=production
      - APP_KEY=base64:your_app_key_here
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=registerappform
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    expose:
      - "9000" # PHP-FPM default port
    depends_on:
      - db
      - cache

  nginx:
    image: nginx:stable-alpine
    container_name: registerappform-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: registerappform-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: registerappform
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33060:3306"

  cache:
    image: redis:latest
    container_name: registerappform-cache
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db_data: